# CI workflow for pull request events
name: CI Pull Request

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      rust-version: 'stable'
