# Legacy CI workflow - now replaced by ci-push.yml and ci-pr.yml
# This file is kept for backwards compatibility but should be deprecated
# The new approach uses separate workflows for push and PR events to avoid duplication

name: ci

on:
  workflow_dispatch:  # Only allow manual triggering

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      rust-version: 'stable'
